# Generated by Django 3.2.23 on 2024-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='day',
            field=models.DateField(default='something', max_length=100),
        ),
    ]
