# Generated by Django 3.2.23 on 2024-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_recipe_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='day',
            field=models.CharField(default='something', max_length=100),
        ),
    ]
